apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      hostname: auth
      containers:
        - name: auth
          image: ghcr.io/hashaneranda/container-apps/exchange/auth:main
          env:
            - name: API_GATEWAY_PORT
              value: "3000"
            - name: AUTH_SERVICE_PORT
              value: "8001"
            - name: AUTH_SERVICE_HOST
              value: auth.kubernetes.internal
            - name: EXCHANGE_SERVICE_PORT
              value: "8002"
            - name: EXCHANGE_SERVICE_HOST
              value: exchange.kubernetes.internal
          ports:
            - containerPort: 8001
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.2"
              memory: 300Mi
            limits:
              cpu: "1.0"
              memory: 300Mi
      serviceAccountName: default

---
apiVersion: v1
kind: Service
metadata:
  name: exchange-auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
