apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      hostname: auth
      containers:
        - name: auth
          image: ghcr.io/hashaneranda/container-apps/exchange/auth:main
          envFrom:
            - secretRef:
                name: exchange-secret
          ports:
            - containerPort: 8001
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      serviceAccountName: default

---
apiVersion: v1
kind: Service
metadata:
  name: exchange-auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
