name: Main Workflow
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: .${{ github.workspace }}/.github/workflows/build-auth.yml
      - run: .${{ github.workspace }}/.github/workflows/build-exchange.yml
      - run: .${{ github.workspace }}/.github/workflows/build-gateway.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ${{ github.workspace }}/.github/workflows/deploy-azure.yml
