name: Main Workflow
on:
  push:
    branches:
      - dev
jobs:
  call-workflow-auth:
    uses: ${{ github.workspace }}/.github/workflows/build-auth.yml@${GITHUB_REF##*/}
  call-workflow-exchange:
    uses: ${{ github.workspace }}/.github/workflows/build-exchange.yml@${GITHUB_REF##*/}
  call-workflow-gateway:
    uses: ${{ github.workspace }}/.github/workflows/build-gateway.yml@${GITHUB_REF##*/}
  call-workflow-deploy:
    uses: ${{ github.workspace }}/.github/workflows/deploy-azure.yml@${GITHUB_REF##*/}
