name: Main Workflow
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-auth.yml@dev
      - uses: ./.github/workflows/build-exchange.yml@dev
      - uses: ./.github/workflows/build-gateway.yml@dev
  deploy:
    needs: build
    steps:
      - uses: ./.github/workflows/deploy-azure.yml@dev
