name: Main Workflow
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: .${{ github.workspace }}/.github/workflows/build-auth.yml@$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
      - uses: .${{ github.workspace }}/.github/workflows/build-exchange.yml@$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
      - uses: .${{ github.workspace }}/.github/workflows/build-gateway.yml@$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ${{ github.workspace }}/.github/workflows/deploy-azure.yml@$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
